### ISSUE TITLE
Adding databases during apk creation?

### ISSUE THREAD

**Issue by Loopho66** [mougino/Basic-compiler#1]
I realized there is no possibility to include a database inside the apk, since the compiler does not ask to include one (or more).
Is it possible to add this feature?

Thanks

**Comment by mougino** [comment]
Hi, this is the first time that I have this request in 8 years...
May I suggest a workaround rather than a new feature that will complexify the compiler?

1. You can copy your database into "rfo-basic/data", then you have the possibility to include it in the compiler.

2. At the start of your program, you can write something like this:

```Basic
FILE.EXISTS fe, "../databases/my_database.db"
IF !fe
  BYTE.OPEN R, fid, "my_database.db"
  BYTE.COPY fid, "../databases/my_database.db"
ENDIF
```
